FROM nginx

ADD https://raw.githubusercontent.com/li0nel/laravel-on-fargate/master/nginx.conf /etc/nginx/
ADD https://raw.githubusercontent.com/li0nel/laravel-on-fargate/master/default.conf /etc/nginx/conf.d/

ADD public /usr/share/nginx/html

WORKDIR /usr/share/nginx/html